### PR TITLE
MRI: Stub out Graphics.play_movie

### PR DESCRIPTION
**Pull request by mook**
Some people are using it to detect the RGSS version.  ([Line 52 in this script](http://a1tktk.web.fc2.com/vxa_scripts/a1_common_script.txt).)

Obviously this doesn't actually play any movies, but it's better than crashing :)

Let me know if I'm making too many PRs or whatever :)

### CODE REVIEW

**Comment by Ancurio** [comment]
> Let me know if I'm making too many PRs or whatever :)

What? No way, contributions are always very welcome! Although the codebase is badly documented so it might unfortunately deter some :)

Also, having separate PRs for fixes towards unrelated parts of the code is definitely the right way to do it.

**Comment by mook** [comment]
Stubbed out in `graphics.cpp` instead, as requested in https://github.com/mook/mkxp/commit/8bd1d9b49d1fcad5a5b0beb752535836f80fbf95.  (Sorry, force push erased it from the PR.)  Also, fixed a problem where I was accidentally exposing it in RGSS2 (which sort of defeats the purpose of the script this was trying to fix).  Thanks for the feedback!

**Comment by Ancurio** [comment]
Ah, right, the force push causes the comments to become disattached from this PR. But no worries, force-pushing is a lot better than what I think github wants us to do (endlessly append "fix" commits onto PRs), because the final commit history stays clean.

Other than the minor tab nitpick, it looks great!

**Comment by mook** [comment]
Tab thing fixed.  Commented because IIRC github doesn't notify on forced push to a PR.

**Comment by Ancurio** [comment]
Thanks for your work!

**Pull request merged**
