### PR TITLE
Font: Fix default fonts for VX+

### PR DESCRIPTION
**Pull request by mathewv**
This commit corrects the default fonts that are expected for VX and VX Ace to UmePlus Gothic and VL Gothic respectively. This improves Japanese support and makes English language games which use the default RTP fonts display text more accurately.

### CODE REVIEW

**Comment by Ancurio** [comment]
Ok, I queried `Font.default_name` in three different RGSS versions:

English RGSS1: `"Arial"`
Japanese RGSS2: `["UmePlus Gothic", "MS ????", "Courier New"]`
English RGSS3: `"VL Gothic"`

Clearly there is some discrepancy between what my code was doing, but I'm not sure your changes fix it fully. Besides, I'm missing some cases alltogether (Japanese 1 and 3, English 2). If I remember correctly, Japanese RGSS1 default was `MS PGothic`. Do you happen to have access to those versions to test it?

And it's obvious that if we want to truly make this more accurate, we will need a config option to specify whether English or Japanese defaults should be used (maybe we can reuse `titleLanguage`? Although that would be hackish.)

**Comment by mathewv** [comment]
Oops, I completely forgot to consider RGSS1 for some reason. No excuses there.

According to the tests, Japanese RGSS1 does indeed use `"MS PGothic"` (though if you want 100% accuracy it's `"ＭＳ Ｐゴシック"`). The English and Japanese font lists for RGSS2 seem to be identical: `["UmePlus Gothic", "MS Gothic", "Courier New"]` (again, if you want 100% accuracy, it's `"ＭＳ ゴシック`"). Japanese RGSS3 only has `"VL Gothic"` just like the English version.

Perhaps a good way to solve the RGSS1 issue is to add an option to override the default font and just leave it as `Arial` internally? Combined with `titleLanguage`, this would essentially allow running mkxp in a "Japanese mode".

**Comment by Ancurio** [comment]
About `MS Pゴシック`; I assume a Japanese Windows system recognizes that string and somehow redirects it toward the same file? I'm wondering whether it makes sense to be **that** accurate.

Anyway, as for the code, I think splitting it into `Font::defaultName` and the custom array stuff in the MRI backend is not the way to go. My code was bad in the first place so it's not your fault, you just tried to fit it into the pattern you saw.

I was expecting the differences between Eng. and Jap. to be bigger, but since it's really just RGSS1 as you said, I think we can postpone that in a FIXME for now.

I'll quickly push a patch myself if that's alright with you?

**Comment by mathewv** [comment]
As far as I can tell, font faces can have embedded names in multiple languages, and lots of Japanese software use the Japanese names. I agree that it's probably better to use the English/Latin character names for the fonts but I wanted to bring it to your attention at least.

Yeah, I don't mind if my stuff is made obsolete by a better solution.

**Comment by Ancurio** [comment]
Can you tell me what kind of script situation you were fixing when writing this patch? Is it only about `Font.default_name`, or is the resulting `name` attribute of a newly created Font also involved?

**Comment by mathewv** [comment]
My patch was made under the assumption that the default font in VX was just `"UmePlus Gothic"` and not an array, so I didn't really consider the value of a newly created `Font.name` when writing it. But according to the tests I just ran, it seems that newly created `Font`s are set to `Font.default_name`, whether it's a single font name or an array, so ideally this would have to be done by mkxp too.

**Comment by Ancurio** [comment]
Sorry for the delay. 5d776319b56473f564c1230116b096b01699c260 should fix the default fonts.

**Comment by mathewv** [comment]
Ah... sorry about all those commits, I thought they would be going to their own separate fork for my own game. But thanks a bunch for fixing the default fonts.

**Pull request closed without merging**
